module Constants
  DATE_FORMAT = '%d-%m-%Y'.freeze
  ZERO = 0
  ONE = 1
  TWO = 2
  THREE = 3

  MUSIC_FREE_PLAN_PRICE = 0
  MUSIC_FREE_PLAN_VALIDITY = 1
  MUSIC_PERSONAL_PLAN_PRICE = 100
  MUSIC_PERSONAL_PLAN_VALIDITY = 1
  MUSIC_PREMIUM_PLAN_PRICE = 250
  MUSIC_PREMIUM_PLAN_VALIDITY = 3

  VIDEO_FREE_PLAN_PRICE = 0
  VIDEO_FREE_PLAN_VALIDITY = 1
  VIDEO_PERSONAL_PLAN_PRICE = 200
  VIDEO_PERSONAL_PLAN_VALIDITY = 1
  VIDEO_PREMIUM_PLAN_PRICE = 500
  VIDEO_PREMIUM_PLAN_VALIDITY = 3

  PODCAST_FREE_PLAN_PRICE = 0
  PODCAST_FREE_PLAN_VALIDITY = 1
  PODCAST_PERSONAL_PLAN_PRICE = 100
  PODCAST_PERSONAL_PLAN_VALIDITY = 1
  PODCAST_PREMIUM_PLAN_PRICE = 300
  PODCAST_PREMIUM_PLAN_VALIDITY = 3

  UPTO_FOUR_DEVICES_PLAN_PRICE_PER_MONTH = 50
  UPTO_TEN_DEVICES_PLAN_PRICE_PER_MONTH = 100
  NOTIFICATION_DAYS_BEFORE = 10

  RENEWAL_AMOUNT = 'RENEWAL_AMOUNT'.freeze
  RENEWAL_REMINDER = 'RENEWAL_REMINDER'.freeze
end
