module Commands
  START_SUBSCRIPTION = 'START_SUBSCRIPTION'.freeze
  ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'.freeze
  ADD_TOPUP = 'ADD_TOPUP'.freeze
  PRINT_RENEWAL_DETAILS = 'PRINT_RENEWAL_DETAILS'.freeze
end
